// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSvviHMk_optnAVfaLtkEIe-Jpsd8jHvE',
    appId: '1:623528099306:web:4e77b2dcc122d56f3c0693',
    messagingSenderId: '623528099306',
    projectId: 'edunova-ai-d2832',
    authDomain: 'edunova-ai-d2832.firebaseapp.com',
    storageBucket: 'edunova-ai-d2832.firebasestorage.app',
    measurementId: 'G-P2SFPLD9V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIP5-S292J5aknmtmUUFmrz4jSnUUnOD0',
    appId: '1:623528099306:android:c6933c45f01abc213c0693',
    messagingSenderId: '623528099306',
    projectId: 'edunova-ai-d2832',
    storageBucket: 'edunova-ai-d2832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQ7_TU1nH8BCg1NAdGjs4yCrT11jvtYA',
    appId: '1:623528099306:ios:51a06a2ea37fe65d3c0693',
    messagingSenderId: '623528099306',
    projectId: 'edunova-ai-d2832',
    storageBucket: 'edunova-ai-d2832.firebasestorage.app',
    iosBundleId: 'com.example.edunovaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXQ7_TU1nH8BCg1NAdGjs4yCrT11jvtYA',
    appId: '1:623528099306:ios:51a06a2ea37fe65d3c0693',
    messagingSenderId: '623528099306',
    projectId: 'edunova-ai-d2832',
    storageBucket: 'edunova-ai-d2832.firebasestorage.app',
    iosBundleId: 'com.example.edunovaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSvviHMk_optnAVfaLtkEIe-Jpsd8jHvE',
    appId: '1:623528099306:web:3f6d32b3112e40013c0693',
    messagingSenderId: '623528099306',
    projectId: 'edunova-ai-d2832',
    authDomain: 'edunova-ai-d2832.firebaseapp.com',
    storageBucket: 'edunova-ai-d2832.firebasestorage.app',
    measurementId: 'G-P7NV484WEJ',
  );
}
